# Generated by Django 3.2.11 on 2022-01-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0002_rename_course_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='Symptom1',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='language',
            new_name='Symptom2',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='price',
        ),
        migrations.AddField(
            model_name='patient',
            name='Symptom3',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
