# Generated by Django 3.2.11 on 2022-01-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_auto_20220107_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Symptom3',
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='Symptom1',
            field=models.CharField(max_length=100),
        ),
    ]
